using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ACSMCOMPONENTS24Lib;
using AXDBLib;
using Autodesk.DesignScript.Runtime;

namespace AMR.dynSSetMgr
{
   
    [IsVisibleInDynamoLibrary(true)]
    public partial class Sheet
    {
        // sheet.Clear();
        [IsVisibleInDynamoLibrary(false)]
        public static void Clear()
        {

        }
        // sheet.GetCustomPropertyBag();
        [IsVisibleInDynamoLibrary(false)]
        public static void GetCustomPropertyBag()
        {

        }
      
        // sheet.GetDirectlyOwnedObjects(out objects);
        [IsVisibleInDynamoLibrary(false)]
        public static void GetDirectlyOwnedObjects()
        {

        }
    
        // sheet.GetIsDirty();
        [IsVisibleInDynamoLibrary(false)]
        public static void GetIsDirty()
        {

        }
        // sheet.GetLayout();
        [IsVisibleInDynamoLibrary(false)]
        public static void GetLayout(Sheet sheet)
        {
            
        }
      
        // sheet.GetObjectId();
        [IsVisibleInDynamoLibrary(false)]
        public static void GetObjectId()
        {

        }
        // sheet.GetOwner();
        [IsVisibleInDynamoLibrary(false)]
        public static void GetOwner()
        {

        }
        // sheet.GetSheetViews();
        [IsVisibleInDynamoLibrary(false)]
        public static void GetSheetViews()
        {

        }
      
        // sheet.GetTypeName();
        [IsVisibleInDynamoLibrary(false)]
        public static void GetTypeName()
        {

        }
        // sheet.InitNew(pOwner);
        [IsVisibleInDynamoLibrary(false)]
        public static void InitNew()
        {

        }
        // sheet.Load(pFiler);
        [IsVisibleInDynamoLibrary(false)]
        public static void Load()
        {

        }
        // sheet.Save(pFiler);
        [IsVisibleInDynamoLibrary(false)]
        public static void Save()
        {

        }
       
        // sheet.SetLayout(pLayoutRef);
        [IsVisibleInDynamoLibrary(false)]
        public static void SetLayout()
        {

        }
        // sheet.SetOwner(pOwner);
        [IsVisibleInDynamoLibrary(false)]
        public static void SetOwner()
        {

        }
        // sheet.SetTitle(title);
        [IsVisibleInDynamoLibrary(false)]
        public static void SetTitle()
        {

        }
        // sheet2.GetCategory();
        [IsVisibleInDynamoLibrary(false)]
        public static void GetCategory()
        {

        }
      
        // sheet2.SetCategory(newVal);
        [IsVisibleInDynamoLibrary(false)]
        public static void SetCategory()
        {

        }
       
    }
}
